### PR TITLE
Upgrade snap to version 7.2.7

### PR DESCRIPTION
**Pull request by dietmarw**
Also updated yaml and structure to avoid deprecation 
warnings.

### CODE REVIEW

**Comment by dietmarw** [comment]
Would be nice if you could also upload the new snap to the store.

**Comment by otfried** [comment]
Snapcraft currently seems to have too many drawbacks:

- contrary to what their PR says, it's very Ubuntu specific

- having to embed latex

Since it didn't solve any problem that the appimage doesn't also solve, i don't want to invest the effort necessary to build them...

**Comment by dietmarw** [comment]
I totally understand. There is actually a new confinement mode called "classic" available with the next snapd which basically lets you access the file system. So you no longer need to embed the LaTeX environment. It is basically a solution of providing a deb like install file without the overcomplicated rules of building a deb. It *should* also run on non-deb systems in that mode but I could not test this. 

I'll probably look at it again  for the next ipe release. Until then your appimage is probably the most lightweight solution. 

If you don't mind I could "overtake" the snap creation as an additional installation option. Not quite sure yet how one overtakes the publishing channel. But this can be found out.

**Comment by otfried** [comment]
I think I can give you rights to release ipe snaps.    I'll look into that when I have time - feel free to remind me in four weeks or so.

**Pull request merged**
